### PR TITLE
Fix settings file

### PR DESCRIPTION
**Pull request by munierujp**
* Add `node_modules` to `.gitignore`
* Add `package-lock.json`
* Add `start` command
* Rename `settings.json.sample` to `settings.sample.json`
For syntax highlight on editor
* Fix settings key
Rename `channels` to `contents`

### CODE REVIEW

**Comment by blue0513** [comment]
@munierujp Thx for fixing it. But this PR has multiple changes. Plz divide into some PRs. 
For example: 

1. Fix the key in settings.json.sample 
2. Rename settings.json.sample
3. Modify git ignore ..... etc

**Comment by munierujp** [comment]
I made other PR #30 for usiing local Electron.

**Comment by blue0513** [comment]
@munierujp Thx merged #30. Can I modify settings.json.sample quickly? (cuz new cloner may be affected by this mistake)

**Comment by blue0513** [comment]
Done it. Should I close this PR?   
Anyway thx for your help

**Comment by munierujp** [comment]
resolved by #31
thanks @bule0513

**Comment by blue0513** [comment]
@munierujp Thx too!

**Pull request closed without merging**
